#!/bin/bash

while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do case $1 in
  -V | --version )
    echo "gh-org-members v1.0.0"
    exit 0
    ;;
  -f | --fullname )
    fullname=true
    shift
    ;;
  -j | --json )
    json=true
    shift
    ;;
  -r | --regexp )
    regexp="$2"
    shift
    shift
    ;;
  -u | --url )
    url=true
    shift
    ;;
  -l | --login )
    login=true
    shift
    ;;
  -w | --orgurl )
    orgurl=true
    shift
    ;;
  -s | --site )
    site=true
    shift
    ;;
  -o | --org )
    org="$2"
    shift
    shift
    ;;
  --default )
    default_org=true
    shift
    ;;
  -h | --help )
    echo "Usage: gh org-members [options] [organization]"
    echo "Options:"
    echo "-V, --version: Output the version number"
    echo "-f, --fullname: Show name of the user (if available)"
    echo "-j, --json: returns the full json object"
    echo "-r, --regexp <regexp>: Only members with some field matching <regexp> will be shown"
    echo "-u, --url: Show github user url"
    echo "-l, --login: Show github user login"
    echo "-w, --orgurl: Show github user url as a member of the org"
    echo "-s, --site: Show url of the members github pages web sites"
    echo "-o, --org <org>: Default organization"
    echo "--default: Set selected 'org' as default organization for future uses"
    echo "-h, --help: Display help for command"
    exit 0
    ;;

esac

# Shift to the next parameter
shift

done

# Main logic of the script can be implemented here

